### ISSUE TITLE
When will the new version or the current version will be released

### ISSUE THREAD

**Issue by keerthinath-ganjam** [Azure/diagnostics-correlation#5]
When will the new version or the current version will be released

**Comment by lmolkova** [comment]
@keerthinath-ganjam 
this repo is abandoned.

There is a new solution integrated now in .NET Core 2.0 (but you may use it on other versions and flavors) and gives you the way to correlate your traces and restore causality between them.

Please check new [Actiity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) class in .NET.
It works together with [DiagnosticSource](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md).

HttpClient in .NET Core is instrumented with DiagnosticSource and Activity. Here is a HTTP diagnostics [guide](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/HttpDiagnosticsGuide.md) in .net core 2.0

Asp.Net Core on incoming boundary is also [instrumented](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/HostingApplication.cs) with DiagnosticSource and Activity.

[ApplicationInsights](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-overview) SDKs for .NET now use this API and instrumentation and natively support correlation with no code modification on .net core and .net full framework.

**Comment by keerthinath-ganjam** [comment]
@lmolkova  - You mean to say that if i update the latest App Insight nugets In any of the app (.NetCore 1.1 or MVC or WEBAPI) the correlation b/w the applications??

**Comment by lmolkova** [comment]
Yes, if you update AppInsights SDKs to the latest available, you would get end-to-end tracing with correlated telemetry across your stack (as long as your apps communicated over HTTP).
